name: A build pipeline for a python project using poetry.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint the python project
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          rm get-poetry.py

      - name: Initialize python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Check formatting
        run: ./ci/check-format.sh

      - name: Run tests
        run: ./ci/test-check.sh
