name: A build pipeline for a python project using poetry.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint the python project
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Initialize python 3.10.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Check formatting
        run: ./ci/check-format.sh

      - name: Run tests
        run: ./ci/test-check.sh
